- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:

    # vim
    ~/.vim: vim
    ~/.vimrc: vim/vimrc

    # Tmux
    ~/.tmux.conf: tmux/tmux.conf
    ~/.tmux/plugins: tmux/plugins
    ~/.tmux/plugins/tpm: tmux/tpm

    #ZSH
    ~/.zshrc: zsh/zshrc
    ~/.p10k.zsh: zsh/p10k.zsh
    ~/.zsh/antigen: zsh/antigen
    ~/.zsh/themes: zsh/themes
    ~/.zsh/aliases: zsh/aliases
    ~/.zsh/plugins: zsh/plugins

    # bash
    ~/.bash:
      force: true
      path: bash
    ~/.bashrc: 
      force: true
      path: bash/bashrc


- shell:
  - git submodule sync --recursive
